server:
  port: 8081
message-broker:
  mqtt:
    max-in-flight: 1000
    client-id: consumer-id-1
    client-endpoint: 192.168.42.135:1883

  consumer:
    student-topic: student-topic
    university-topic: university-topic
