server:
  port: 8083

message-broker:
  mqtt:
    max-in-flight: 1000
    client-id: producer-id-1
    client-endpoint: 192.168.42.135:1883

  producer:
    student-topic: student-topic
    university-topic: university-topic
